ALTER TABLE IF EXISTS credits DROP CONSTRAINT IF EXISTS credits_user_id_key;
ALTER TABLE credits DROP CONSTRAINT IF EXISTS credits_user_id_key;
DELETE FROM credits a USING credits b WHERE a.user_id = b.user_id AND a.created_at < b.created_at;
ALTER TABLE credits ADD CONSTRAINT credits_user_id_key UNIQUE (user_id);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'credits' AND column_name = 'total_credits') THEN ALTER TABLE credits ADD COLUMN total_credits INTEGER NOT NULL DEFAULT 0; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'credits' AND column_name = 'used_credits') THEN ALTER TABLE credits ADD COLUMN used_credits INTEGER NOT NULL DEFAULT 0; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'credits' AND column_name = 'remaining_credits') THEN ALTER TABLE credits ADD COLUMN remaining_credits INTEGER NOT NULL DEFAULT 0; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'credits' AND column_name = 'created_at') THEN ALTER TABLE credits ADD COLUMN created_at TIMESTAMPTZ DEFAULT now(); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'credits' AND column_name = 'updated_at') THEN ALTER TABLE credits ADD COLUMN updated_at TIMESTAMPTZ DEFAULT now(); END IF; END $$;
UPDATE credits SET total_credits = COALESCE(amount, 0), used_credits = COALESCE(used, 0), remaining_credits = COALESCE(remaining, 0) WHERE total_credits IS NULL OR total_credits = 0;
CREATE TABLE IF NOT EXISTS transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, amount INTEGER NOT NULL, transaction_type TEXT NOT NULL CHECK (transaction_type IN ('purchase', 'deduction', 'refund')), feature_name TEXT, description TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_credits_user_id ON credits(user_id);
ALTER TABLE IF EXISTS transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own transactions" ON transactions;
CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own transactions" ON transactions;
CREATE POLICY "Users can insert own transactions" ON transactions FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can view own credits" ON credits;
CREATE POLICY "Users can view own credits" ON credits FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own credits" ON credits;
CREATE POLICY "Users can insert own credits" ON credits FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own credits" ON credits;
CREATE POLICY "Users can update own credits" ON credits FOR UPDATE USING (auth.uid() = user_id);
CREATE OR REPLACE FUNCTION update_credits_updated_at() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS trigger_credits_updated_at ON credits;
CREATE TRIGGER trigger_credits_updated_at BEFORE UPDATE ON credits FOR EACH ROW EXECUTE FUNCTION update_credits_updated_at();